name: CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 14.21.x
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build

  lint:
    name: Lint
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 14.21.x
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  test:
    name: Test on OS ${{ matrix.os }} with NodeJS ${{ matrix.node-version }}
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # See <https://nodejs.org/en/about/releases/>
        node-version: [16.20.2, 18.19.0, 20.10.0]
        # See <https://github.com/actions/runner-images#available-images>
        os: [ubuntu-22.04, windows-2022, macos-12]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test
